server:
  port: 8888
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
